[package]
name = "person_rust_skeleton"
version = "0.1.0"
authors = ["Michael Cummings <dragonrun1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
