table! {
    /// Representation of the `genders` table.
    ///
    /// (Automatically generated by Diesel.)
    genders (id) {
        /// The `id` column of the `genders` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Char,
        /// The `gender_identity` column of the `genders` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        gender_identity -> Nullable<Varchar>,
        /// The `sex` column of the `genders` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        sex -> Varchar,
        /// The `created_at` column of the `genders` table.
        ///
        /// Its SQL type is `Datetime`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Datetime,
    }
}

table! {
    /// Representation of the `people` table.
    ///
    /// (Automatically generated by Diesel.)
    people (id) {
        /// The `id` column of the `people` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Char,
        /// The `additional_name` column of the `people` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        additional_name -> Nullable<Varchar>,
        /// The `birthday` column of the `people` table.
        ///
        /// Its SQL type is `Nullable<Datetime>`.
        ///
        /// (Automatically generated by Diesel.)
        birthday -> Nullable<Datetime>,
        /// The `family_name` column of the `people` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        family_name -> Varchar,
        /// The `gender_id` column of the `people` table.
        ///
        /// Its SQL type is `Nullable<Char>`.
        ///
        /// (Automatically generated by Diesel.)
        gender_id -> Nullable<Char>,
        /// The `given_name` column of the `people` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        given_name -> Varchar,
        /// The `honorific_prefix` column of the `people` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        honorific_prefix -> Nullable<Varchar>,
        /// The `honorific_suffix` column of the `people` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        honorific_suffix -> Nullable<Varchar>,
        /// The `pronoun_id` column of the `people` table.
        ///
        /// Its SQL type is `Nullable<Char>`.
        ///
        /// (Automatically generated by Diesel.)
        pronoun_id -> Nullable<Char>,
        /// The `created_at` column of the `people` table.
        ///
        /// Its SQL type is `Datetime`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Datetime,
    }
}

table! {
    /// Representation of the `pronouns` table.
    ///
    /// (Automatically generated by Diesel.)
    pronouns (id) {
        /// The `id` column of the `pronouns` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Char,
        /// The `object` column of the `pronouns` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        object -> Varchar,
        /// The `possessive` column of the `pronouns` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        possessive -> Varchar,
        /// The `subject` column of the `pronouns` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        subject -> Varchar,
        /// The `created_at` column of the `pronouns` table.
        ///
        /// Its SQL type is `Datetime`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Datetime,
    }
}

joinable!(people -> genders (gender_id));
joinable!(people -> pronouns (pronoun_id));

allow_tables_to_appear_in_same_query!(
    genders,
    people,
    pronouns,
);
